version: "3.4"

services:
  backend:
    image: pelish/match-backend:latest
    # build:
    #   context: ./match-api
    #   dockerfile: Dockerfile
    command: gunicorn app:app --timeout 300 --bind 0.0.0.0:5000
    expose:
      - 5000
    ports:
      - "5000:5000"
  nginx:
    image: nginx:1.24.0-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
